-- local ls = require 'luasnip'
-- local t = ls.text_node
-- local i = ls.insert_node
-- local s = ls.snippet

-- ls.add_snippets('markdown', {
--   s('codeblock', {
--     t { '```' },
--     i(1),
--     t { '', '' },
--     i(2),
--     t { '', '' },
--   }),
-- })
