local color = require('blueberry.config').colors

local components = {}

local left_sep = '  '

-- require('feline').setup {
--   preset = 'noicon',
--   force_inactive = {
--     bufnames = {},
--     buftypes = { 'help', 'prompt', 'terminal' },
--     filetypes = {
--       'NvimTree',
--     },
--   },
--   disable = {
--     filetypes = { 'NvimTree' },
--   },
--   colors = {
--     bg = color.bg,
--     fg = color.gray1,
--   },
--   vi_mode_colors = {
--     NORMAL = 'green',
--     OP = 'green',
--     INSERT = 'red',
--     VISUAL = 'skyblue',
--     LINES = 'skyblue',
--     BLOCK = 'skyblue',
--     REPLACE = 'violet',
--     ['V-REPLACE'] = 'violet',
--     ENTER = 'cyan',
--     MORE = 'cyan',
--     SELECT = 'orange',
--     COMMAND = 'green',
--     SHELL = 'green',
--     TERM = 'green',
--     NONE = 'yellow',
--   },
--   components = {
--     inactive = {
--       {
--         {
--           provider = 'diagnostic_hints',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'diagnostic_info',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'diagnostic_warnings',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'diagnostic_errors',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'git_branch',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'git_diff_added',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'git_diff_changed',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'git_diff_removed',
--           left_sep = left_sep,
--         },
--         {
--           provider = 'file_info',
--           left_sep = left_sep,
--         },
--       },
--     },
--     active = {
--       {
--         {
--           provider = 'diagnostic_hints',
--           left_sep = ' ',
--         },
--         {
--           provider = 'diagnostic_info',
--           left_sep = ' ',
--         },
--         {
--           provider = 'diagnostic_warnings',
--           left_sep = ' ',
--         },
--         {
--           provider = 'diagnostic_errors',
--           left_sep = ' ',
--         },
--         {
--           provider = 'git_branch',
--           left_sep = ' ',
--         },
--         {
--           provider = 'git_diff_added',
--           left_sep = ' ',
--         },
--         {
--           provider = 'git_diff_changed',
--           left_sep = ' ',
--         },
--         {
--           provider = 'git_diff_removed',
--           left_sep = ' ',
--         },
--         {
--           provider = 'file_info',
--           left_sep = ' ',
--         },
--       },
--       {
--         {
--           provider = 'file_encoding',
--           right_sep = ' ',
--         },
--         {
--           provider = function()
--             return vim.bo.filetype
--           end,
--           right_sep = ' ',
--         },
--         {
--           provider = 'position',
--           right_sep = ' ',
--         },
--         {
--           provider = function()
--             return require('feline.providers.vi_mode').get_vim_mode()
--           end,
--           right_sep = ' ',
--         },
--       },
--     },
--   },
-- }
