require('ibl').setup {
  -- show_first_indent_level = false,
  scope = { enabled = false },
  exclude = {
    filetypes = {
      'NvimTree',
      'terminal',
      'toggleterm',
      'glowpreview',
      'help',
      'lazy',
      'mason',
    },
  },
  -- context_patterns = {
  --   'class',
  --   '^func',
  --   'method',
  --   '^if',
  --   'while',
  --   'for',
  --   'with',
  --   'try',
  --   'except',
  --   'arguments',
  --   'argument_list',
  --   'object',
  --   'dictionary',
  --   'element',
  --   'table',
  --   'tuple',
  --   -- Rescript
  --   'type_declaration',
  --   'module_declaration',
  --   'block',
  --   'switch_match',
  --   'jsx_fragment',
  -- },
}
