require('indent_blankline').setup {
  show_current_context = true,
  show_first_indent_level = false,
  filetype_exclude = {
    'NvimTree',
    'lsp-installer',
    'terminal',
    'toggleterm',
    'glowpreview',
    'tsplayground',
    'help',
    'lazy',
    'mason',
  },
  context_patterns = {
    'class',
    '^func',
    'method',
    '^if',
    'while',
    'for',
    'with',
    'try',
    'except',
    'arguments',
    'argument_list',
    'object',
    'dictionary',
    'element',
    'table',
    'tuple',
    -- Rescript
    'type_declaration',
    'module_declaration',
    'block',
    'switch_match',
    'jsx_fragment',
  },
}
