add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" 

[directory]
read_only = " "
truncation_length = 8
truncate_to_repo = false

[battery]
disabled = true

[rlang]
disabled = true
